# Copyright (c) 2018-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

###
# Builder Image
#
FROM node:10.16-alpine

# Add npm global bin directory to the path
ENV HOME=/home/theia-dev \
    PATH=/home/theia-dev/.npm-global/bin:${PATH} \
    # Specify the directory of git (avoid to search at init of Theia)
    USE_LOCAL_GIT=true \
    LOCAL_GIT_DIRECTORY=/usr \
    GIT_EXEC_PATH=/usr/libexec/git-core \
    THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=true

RUN apk add --update --no-cache \
    # Download some files
    curl \
    # To play with json in shell
    jq \
    # compile some javascript native stuff (node-gyp)
    make gcc g++ python \
    # clone repositories (and also using ssh repositories)
    git openssh openssh-keygen \
    # Handle git diff properly
    less \
    # bash shell
    bash \
    # give root privilege
    sudo \
    # for useradd command
    shadow \
    # some lib to compile 'native-keymap' npm mpdule
    libx11-dev libxkbfile-dev && \
    useradd -u 1001 -U -G root -d ${HOME} -s /bin/bash theia-dev && \
    apk del --no-cache shadow && \
    echo "%root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Define package of the theia generator to use
COPY generator/eclipse-che-theia-generator.tgz ${HOME}/eclipse-che-theia-generator.tgz

WORKDIR ${HOME}

# Exposing Theia ports
EXPOSE 3000 3030

# Configure npm and yarn to use home folder for global dependencies
RUN npm config set prefix "${HOME}/.npm-global" && \
    echo "--global-folder \"${HOME}/.yarn-global\"" > ${HOME}/.yarnrc && \
    # add eclipse che theia generator
    yarn global add yo @theia/generator-plugin@0.0.1-1540209403 file:${HOME}/eclipse-che-theia-generator.tgz && \
    # Generate .passwd.template \
    sed -e "s#^theia-dev:x.*#theia-dev:x:\${USER_ID}:\${GROUP_ID}::${HOME}:/bin/bash#g" \
        /etc/passwd > /.passwd.template && \
    sed -e 's#^theia-dev:.*#theia-dev:x:${GROUP_ID}:#g' \
        /etc/group > /.group.template && \
    mkdir /projects && \
    # Change permissions to let any arbitrary user
    for f in "${HOME}" /projects /etc/passwd /etc/group; do \
        echo "Changing permissions on ${f}" && \
        chgrp -R 0 ${f} && \
        chmod -R g+rwX ${f}; \
    done

WORKDIR "/projects"

ADD src/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD tail -f /dev/null
